.TH QNETLOAD 1
.SH NAME
qnetload \- Graphically display network speed and usage
.SH SYNOPSIS
\fBqnetload\fR
.SH DESCRIPTION
Graphically display network speed and usage.

.TP
\fB-i\fR, \fB\-\-interface=\fIINTERFACE\fR
Display network INTERFACE. For example: eth0, wlan0. If unsure, do not specify.

When running the interface can be changed by clicking on it. Right-click on the interface to list the available interfaces.

.TP
\fB-h\fR, \fB\-\-help\fR
Display help for commandline options.
.TP
\fB-v\fR, \fB\-\-version\fR
Display version information.
.TP
\fB\-\-help\-all\fR
Display help including Qt-specific options.
.PP

.SH USING QNETLOAD
Some features on qnetload might not obvious:
.RS 2
.IP \(bu 2
Click on the interface to change it.
.IP \(bu 2
Right-click anywhere on qnetload to display a contextual menu with the list of interfaces, the IP and the version. The most common interfaces are in bold (ethX, wlanX, etc.).
.IP \(bu 2
There are two buttons: pause the accumulative counter of Downloaded and Uploaded data and reset the counter. To reset the counters, click twice.
.IP \(bu 2
Clicking in the graph will display how much data has been downloaded and uploaded since the position of the click and a projection for the next hour's usage.
.IP \(bu 2
Hover the mouse pointer over any of the numbers to display the meaning of the value.

.SH ORIGINAL IDEA FROM XNETLOAD
\fBqnetload\fR has the same look and feel as \fBxnetload\fR, which is no longer maintained. The \fIq\fP in the name is because \fBqnetload\fR is implemented using the Qt libraries.

.SH FILES
.TP
.I ${HOME}/.config/qnetload/qnetload.conf
The last-used interface is saved here. This will be used the next time \fBqnetload\fR is executed.
.TP
.I /proc/net/dev
This file, provided by the kernel, contains details of the network usage and is read by qnetload to provide the displayed data.
.SH BUG REPORTS
.PP
Bug tracker: <https://github.com/cpina/qnetload/issues>
.br
Email: Carles Pina i Estany <carles@pina.cat>

.SH SEE ALSO
.BR ipmon (1)
.BR ethstatus (1)
.BR nload (1)

.SH ACKNOWLEDGEMENTS
Many thanks to R.F. Smith for xnetload: lots of inspiration from it.

Many thanks to Jen Thomas for testing qnetload and helping with the manual page and texts.

.SH COPYRIGHT AND LICENSE
.PP
Copyright \[co] 2017-2023 Carles Pina i Estany <carles@pina.cat>.
License: GPLv3+: GNU GPL version 3 or later.
