name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v4.1.0
    - name: Install dependencies
      run: |
        sudo apt-get install cmake qt6-base-dev libgl1-mesa-dev
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ../src
        make
